# Generated by Django 5.2.8 on 2025-11-22 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('link', 'External Link'), ('video', 'Video')], max_length=10)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='portfolio/documents/')),
                ('video_url', models.URLField(blank=True)),
                ('external_link', models.URLField(blank=True)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_duration', models.CharField(blank=True, help_text='e.g., 2 weeks, 1 month', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
