# Generated by Django 5.2.8 on 2025-11-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='skills_used',
            field=models.ManyToManyField(blank=True, related_name='portfolio_items', to='skills.skill'),
        ),
    ]
