# Generated by Django 5.2.8 on 2025-11-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioview',
            name='portfolio_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfolio.portfolioitem'),
        ),
        migrations.AddIndex(
            model_name='portfolioview',
            index=models.Index(fields=['portfolio_item', 'viewed_at'], name='portfolio_p_portfol_43871b_idx'),
        ),
    ]
